//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/BGS_Cab_Template/InputAssets/BGSCabinetInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BGSCabinetInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BGSCabinetInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BGSCabinetInput"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""14889345-f1a5-427c-8385-6da706ab100f"",
            ""actions"": [
                {
                    ""name"": ""Stick"",
                    ""type"": ""Value"",
                    ""id"": ""90f62a1b-b592-4894-af2e-c0c20a592c73"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BottomRow1"",
                    ""type"": ""Button"",
                    ""id"": ""896e22ee-fcff-4576-9e40-ee2b8860ea64"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BottomRow2"",
                    ""type"": ""Button"",
                    ""id"": ""931422a8-5edd-4da2-b5ff-c7550f588e1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TopRow1"",
                    ""type"": ""Button"",
                    ""id"": ""8d468531-548b-4ae1-beac-c13ae1b54992"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TopRow2"",
                    ""type"": ""Button"",
                    ""id"": ""928d94ec-cd22-4994-bada-3945fc77acf8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TopRow3"",
                    ""type"": ""Button"",
                    ""id"": ""7f614ab4-c3ec-4147-875b-75a9b3817f15"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BottomRow3"",
                    ""type"": ""Button"",
                    ""id"": ""ea23a3b8-9154-44de-aaf8-d767fe04c006"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayerButton"",
                    ""type"": ""Button"",
                    ""id"": ""91c0f87f-0ad7-41e3-bc3b-41da0ad7a717"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CoinSlot"",
                    ""type"": ""Button"",
                    ""id"": ""1255eaa1-f6ca-4b60-89d9-2c73fbbec751"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d3ac15b3-6949-4660-9c5e-60d872a90a0d"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6bbbce5-e369-4f0a-b68e-ad2f323369ca"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aba67817-3906-46f3-b484-8b8bc6fd917d"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05a87820-acea-4c9c-885c-f9f117b0b50a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e30bd69b-a386-40f5-87a6-07754f14c77c"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dce3ec64-9779-4565-8285-411afd03beb8"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a42c6ac-b682-4e45-9d6b-c3ffb3242d42"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7c8ed4e-80a7-4105-b2ea-52f7b3e0e89f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd80289d-3ec1-4ea5-8a08-01ecd6d98c2b"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46b61d22-3f57-4e7e-8ac1-27d0cfab0c20"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""257e58a4-a1c1-4abe-bf7e-42f4f7ae9104"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4403e60f-5990-4274-8e30-7d06246a9614"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb42966c-33a6-44c4-9e02-815d73bbd0d0"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a301648-73e8-4e7a-a366-43f92c207f60"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e27d5a61-2fcf-4b17-8be4-3ffc8d93e025"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoinSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50f7355b-12ae-4d9c-977c-f52b8a926944"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoinSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e6d6890-043d-4247-b4ed-f75183bec98e"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""3db7552b-a926-4194-9b29-74e3bc56b18c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""958683c3-cd81-4869-bfc6-34178907be69"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""237e5b4c-4ee4-4be2-a51f-3571a5bea963"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1f27d195-3076-4716-b96e-a690ea244bf5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a102e2a8-30a5-4f04-8912-fece7ba8f1ff"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5cd0067d-6adb-4e26-88da-985c73ddd6a9"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""LinuxGameplay"",
            ""id"": ""909ee633-6da0-4253-9914-819bbbae4cb1"",
            ""actions"": [
                {
                    ""name"": ""Stick"",
                    ""type"": ""Value"",
                    ""id"": ""79966f22-0b23-41f9-9006-61e3da8f34ee"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BottomRow1"",
                    ""type"": ""Button"",
                    ""id"": ""39e3a6f5-20bc-4439-a035-a741fcb1d14c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BottomRow2"",
                    ""type"": ""Button"",
                    ""id"": ""288f21ca-5ed5-4358-b9cb-cf9cbfb547de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TopRow1"",
                    ""type"": ""Button"",
                    ""id"": ""d3aaaf79-aeb0-47cb-b01f-27040fe8cb57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TopRow2"",
                    ""type"": ""Button"",
                    ""id"": ""6c93557a-cf05-47a3-b8d9-817c00e37681"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TopRow3"",
                    ""type"": ""Button"",
                    ""id"": ""9108be52-33d3-4d46-bc83-a43715db130f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BottomRow3"",
                    ""type"": ""Button"",
                    ""id"": ""e2d6040a-aac0-418c-8749-8e1b5d2c8aac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayerButton"",
                    ""type"": ""Button"",
                    ""id"": ""298cdb78-fd4c-4848-add3-1a764755ff66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CoinSlot"",
                    ""type"": ""Button"",
                    ""id"": ""e6fdee3f-62a0-4090-bf1f-0bd2b1973b8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7bb65070-69b3-44c8-904a-f8b8754e514d"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c644b75c-43bc-42c1-a616-b9e3ce6f9e79"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a42dd0b-0681-4c44-aa18-5f95721a25eb"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5307117-21ca-4e30-a427-c3891235fd18"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4f3015c-ae35-4d06-8474-13a8a9c6e0f3"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f65c66fa-d53f-44b8-a819-15ee2f27f5ef"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9de1b33-b12a-4867-866f-86f80cfd5901"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c785f99f-1f7c-4c74-91ff-7e96c2f80986"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9a1a134-d912-4eda-9fc4-50208aa10e07"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5991cf48-ba6e-461b-bc13-057dad6038c1"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d9bbcca-4a56-4ea1-b58a-a7f6d9b935a5"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62a5df54-3498-498b-8b4d-d0f90d98410f"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""566e3257-81a9-4ab0-bb4c-a3388414f2ea"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a12600a-be59-4a95-b2c0-d0e7da197738"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2812fa0-9212-4be1-a5dd-f7a03e429d9c"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TopRow3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61a34a5e-591b-472c-9d14-a33284983396"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e457f1e5-a96d-4450-8ff0-1dae26dd8e2a"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1da4c751-dc64-438a-b6d9-aa23f5cc5150"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BottomRow3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a249410-a500-44a2-a82e-f56415ca70af"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6ce4be3-1cc8-45d1-b7b4-3b3026f59d51"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a63b0556-587f-4c32-a759-59849d568e23"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""753445aa-106b-4acc-87ed-ad040e58cdb0"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoinSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37ffd60b-2637-4e3a-aa4b-5db07a7e8b42"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoinSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92aec83f-7463-4992-973c-884da941fef7"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoinSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82b85073-bac5-4875-b2de-c159acc1b587"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""09b9c49d-ab83-45e2-ad4c-27e60fcb80b6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""37ee398d-82ce-467f-a70c-f71b3b0e8a2d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""741bd641-31d6-4a9f-8ac5-390e3c8eee8c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""45ef6dfc-e6cb-43f3-8855-6d58e542bd54"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""81174cb0-5153-48c1-a9b3-e0b777cca8ae"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""cf174093-8fe0-42e2-8d24-00cb38a8e135"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""5b4a08a8-a5c8-4a5e-a9e3-29fe58f2291c"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""9c2c3f5a-f174-4235-8528-d221c67fa494"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c77ef875-74d2-4bed-8978-3a84918e474e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Stick = m_Gameplay.FindAction("Stick", throwIfNotFound: true);
        m_Gameplay_BottomRow1 = m_Gameplay.FindAction("BottomRow1", throwIfNotFound: true);
        m_Gameplay_BottomRow2 = m_Gameplay.FindAction("BottomRow2", throwIfNotFound: true);
        m_Gameplay_TopRow1 = m_Gameplay.FindAction("TopRow1", throwIfNotFound: true);
        m_Gameplay_TopRow2 = m_Gameplay.FindAction("TopRow2", throwIfNotFound: true);
        m_Gameplay_TopRow3 = m_Gameplay.FindAction("TopRow3", throwIfNotFound: true);
        m_Gameplay_BottomRow3 = m_Gameplay.FindAction("BottomRow3", throwIfNotFound: true);
        m_Gameplay_PlayerButton = m_Gameplay.FindAction("PlayerButton", throwIfNotFound: true);
        m_Gameplay_CoinSlot = m_Gameplay.FindAction("CoinSlot", throwIfNotFound: true);
        // LinuxGameplay
        m_LinuxGameplay = asset.FindActionMap("LinuxGameplay", throwIfNotFound: true);
        m_LinuxGameplay_Stick = m_LinuxGameplay.FindAction("Stick", throwIfNotFound: true);
        m_LinuxGameplay_BottomRow1 = m_LinuxGameplay.FindAction("BottomRow1", throwIfNotFound: true);
        m_LinuxGameplay_BottomRow2 = m_LinuxGameplay.FindAction("BottomRow2", throwIfNotFound: true);
        m_LinuxGameplay_TopRow1 = m_LinuxGameplay.FindAction("TopRow1", throwIfNotFound: true);
        m_LinuxGameplay_TopRow2 = m_LinuxGameplay.FindAction("TopRow2", throwIfNotFound: true);
        m_LinuxGameplay_TopRow3 = m_LinuxGameplay.FindAction("TopRow3", throwIfNotFound: true);
        m_LinuxGameplay_BottomRow3 = m_LinuxGameplay.FindAction("BottomRow3", throwIfNotFound: true);
        m_LinuxGameplay_PlayerButton = m_LinuxGameplay.FindAction("PlayerButton", throwIfNotFound: true);
        m_LinuxGameplay_CoinSlot = m_LinuxGameplay.FindAction("CoinSlot", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Newaction = m_UI.FindAction("New action", throwIfNotFound: true);
    }

    ~@BGSCabinetInput()
    {
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, BGSCabinetInput.Gameplay.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_LinuxGameplay.enabled, "This will cause a leak and performance issues, BGSCabinetInput.LinuxGameplay.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, BGSCabinetInput.UI.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Stick;
    private readonly InputAction m_Gameplay_BottomRow1;
    private readonly InputAction m_Gameplay_BottomRow2;
    private readonly InputAction m_Gameplay_TopRow1;
    private readonly InputAction m_Gameplay_TopRow2;
    private readonly InputAction m_Gameplay_TopRow3;
    private readonly InputAction m_Gameplay_BottomRow3;
    private readonly InputAction m_Gameplay_PlayerButton;
    private readonly InputAction m_Gameplay_CoinSlot;
    public struct GameplayActions
    {
        private @BGSCabinetInput m_Wrapper;
        public GameplayActions(@BGSCabinetInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Stick => m_Wrapper.m_Gameplay_Stick;
        public InputAction @BottomRow1 => m_Wrapper.m_Gameplay_BottomRow1;
        public InputAction @BottomRow2 => m_Wrapper.m_Gameplay_BottomRow2;
        public InputAction @TopRow1 => m_Wrapper.m_Gameplay_TopRow1;
        public InputAction @TopRow2 => m_Wrapper.m_Gameplay_TopRow2;
        public InputAction @TopRow3 => m_Wrapper.m_Gameplay_TopRow3;
        public InputAction @BottomRow3 => m_Wrapper.m_Gameplay_BottomRow3;
        public InputAction @PlayerButton => m_Wrapper.m_Gameplay_PlayerButton;
        public InputAction @CoinSlot => m_Wrapper.m_Gameplay_CoinSlot;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Stick.started += instance.OnStick;
            @Stick.performed += instance.OnStick;
            @Stick.canceled += instance.OnStick;
            @BottomRow1.started += instance.OnBottomRow1;
            @BottomRow1.performed += instance.OnBottomRow1;
            @BottomRow1.canceled += instance.OnBottomRow1;
            @BottomRow2.started += instance.OnBottomRow2;
            @BottomRow2.performed += instance.OnBottomRow2;
            @BottomRow2.canceled += instance.OnBottomRow2;
            @TopRow1.started += instance.OnTopRow1;
            @TopRow1.performed += instance.OnTopRow1;
            @TopRow1.canceled += instance.OnTopRow1;
            @TopRow2.started += instance.OnTopRow2;
            @TopRow2.performed += instance.OnTopRow2;
            @TopRow2.canceled += instance.OnTopRow2;
            @TopRow3.started += instance.OnTopRow3;
            @TopRow3.performed += instance.OnTopRow3;
            @TopRow3.canceled += instance.OnTopRow3;
            @BottomRow3.started += instance.OnBottomRow3;
            @BottomRow3.performed += instance.OnBottomRow3;
            @BottomRow3.canceled += instance.OnBottomRow3;
            @PlayerButton.started += instance.OnPlayerButton;
            @PlayerButton.performed += instance.OnPlayerButton;
            @PlayerButton.canceled += instance.OnPlayerButton;
            @CoinSlot.started += instance.OnCoinSlot;
            @CoinSlot.performed += instance.OnCoinSlot;
            @CoinSlot.canceled += instance.OnCoinSlot;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Stick.started -= instance.OnStick;
            @Stick.performed -= instance.OnStick;
            @Stick.canceled -= instance.OnStick;
            @BottomRow1.started -= instance.OnBottomRow1;
            @BottomRow1.performed -= instance.OnBottomRow1;
            @BottomRow1.canceled -= instance.OnBottomRow1;
            @BottomRow2.started -= instance.OnBottomRow2;
            @BottomRow2.performed -= instance.OnBottomRow2;
            @BottomRow2.canceled -= instance.OnBottomRow2;
            @TopRow1.started -= instance.OnTopRow1;
            @TopRow1.performed -= instance.OnTopRow1;
            @TopRow1.canceled -= instance.OnTopRow1;
            @TopRow2.started -= instance.OnTopRow2;
            @TopRow2.performed -= instance.OnTopRow2;
            @TopRow2.canceled -= instance.OnTopRow2;
            @TopRow3.started -= instance.OnTopRow3;
            @TopRow3.performed -= instance.OnTopRow3;
            @TopRow3.canceled -= instance.OnTopRow3;
            @BottomRow3.started -= instance.OnBottomRow3;
            @BottomRow3.performed -= instance.OnBottomRow3;
            @BottomRow3.canceled -= instance.OnBottomRow3;
            @PlayerButton.started -= instance.OnPlayerButton;
            @PlayerButton.performed -= instance.OnPlayerButton;
            @PlayerButton.canceled -= instance.OnPlayerButton;
            @CoinSlot.started -= instance.OnCoinSlot;
            @CoinSlot.performed -= instance.OnCoinSlot;
            @CoinSlot.canceled -= instance.OnCoinSlot;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // LinuxGameplay
    private readonly InputActionMap m_LinuxGameplay;
    private List<ILinuxGameplayActions> m_LinuxGameplayActionsCallbackInterfaces = new List<ILinuxGameplayActions>();
    private readonly InputAction m_LinuxGameplay_Stick;
    private readonly InputAction m_LinuxGameplay_BottomRow1;
    private readonly InputAction m_LinuxGameplay_BottomRow2;
    private readonly InputAction m_LinuxGameplay_TopRow1;
    private readonly InputAction m_LinuxGameplay_TopRow2;
    private readonly InputAction m_LinuxGameplay_TopRow3;
    private readonly InputAction m_LinuxGameplay_BottomRow3;
    private readonly InputAction m_LinuxGameplay_PlayerButton;
    private readonly InputAction m_LinuxGameplay_CoinSlot;
    public struct LinuxGameplayActions
    {
        private @BGSCabinetInput m_Wrapper;
        public LinuxGameplayActions(@BGSCabinetInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Stick => m_Wrapper.m_LinuxGameplay_Stick;
        public InputAction @BottomRow1 => m_Wrapper.m_LinuxGameplay_BottomRow1;
        public InputAction @BottomRow2 => m_Wrapper.m_LinuxGameplay_BottomRow2;
        public InputAction @TopRow1 => m_Wrapper.m_LinuxGameplay_TopRow1;
        public InputAction @TopRow2 => m_Wrapper.m_LinuxGameplay_TopRow2;
        public InputAction @TopRow3 => m_Wrapper.m_LinuxGameplay_TopRow3;
        public InputAction @BottomRow3 => m_Wrapper.m_LinuxGameplay_BottomRow3;
        public InputAction @PlayerButton => m_Wrapper.m_LinuxGameplay_PlayerButton;
        public InputAction @CoinSlot => m_Wrapper.m_LinuxGameplay_CoinSlot;
        public InputActionMap Get() { return m_Wrapper.m_LinuxGameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LinuxGameplayActions set) { return set.Get(); }
        public void AddCallbacks(ILinuxGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_LinuxGameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LinuxGameplayActionsCallbackInterfaces.Add(instance);
            @Stick.started += instance.OnStick;
            @Stick.performed += instance.OnStick;
            @Stick.canceled += instance.OnStick;
            @BottomRow1.started += instance.OnBottomRow1;
            @BottomRow1.performed += instance.OnBottomRow1;
            @BottomRow1.canceled += instance.OnBottomRow1;
            @BottomRow2.started += instance.OnBottomRow2;
            @BottomRow2.performed += instance.OnBottomRow2;
            @BottomRow2.canceled += instance.OnBottomRow2;
            @TopRow1.started += instance.OnTopRow1;
            @TopRow1.performed += instance.OnTopRow1;
            @TopRow1.canceled += instance.OnTopRow1;
            @TopRow2.started += instance.OnTopRow2;
            @TopRow2.performed += instance.OnTopRow2;
            @TopRow2.canceled += instance.OnTopRow2;
            @TopRow3.started += instance.OnTopRow3;
            @TopRow3.performed += instance.OnTopRow3;
            @TopRow3.canceled += instance.OnTopRow3;
            @BottomRow3.started += instance.OnBottomRow3;
            @BottomRow3.performed += instance.OnBottomRow3;
            @BottomRow3.canceled += instance.OnBottomRow3;
            @PlayerButton.started += instance.OnPlayerButton;
            @PlayerButton.performed += instance.OnPlayerButton;
            @PlayerButton.canceled += instance.OnPlayerButton;
            @CoinSlot.started += instance.OnCoinSlot;
            @CoinSlot.performed += instance.OnCoinSlot;
            @CoinSlot.canceled += instance.OnCoinSlot;
        }

        private void UnregisterCallbacks(ILinuxGameplayActions instance)
        {
            @Stick.started -= instance.OnStick;
            @Stick.performed -= instance.OnStick;
            @Stick.canceled -= instance.OnStick;
            @BottomRow1.started -= instance.OnBottomRow1;
            @BottomRow1.performed -= instance.OnBottomRow1;
            @BottomRow1.canceled -= instance.OnBottomRow1;
            @BottomRow2.started -= instance.OnBottomRow2;
            @BottomRow2.performed -= instance.OnBottomRow2;
            @BottomRow2.canceled -= instance.OnBottomRow2;
            @TopRow1.started -= instance.OnTopRow1;
            @TopRow1.performed -= instance.OnTopRow1;
            @TopRow1.canceled -= instance.OnTopRow1;
            @TopRow2.started -= instance.OnTopRow2;
            @TopRow2.performed -= instance.OnTopRow2;
            @TopRow2.canceled -= instance.OnTopRow2;
            @TopRow3.started -= instance.OnTopRow3;
            @TopRow3.performed -= instance.OnTopRow3;
            @TopRow3.canceled -= instance.OnTopRow3;
            @BottomRow3.started -= instance.OnBottomRow3;
            @BottomRow3.performed -= instance.OnBottomRow3;
            @BottomRow3.canceled -= instance.OnBottomRow3;
            @PlayerButton.started -= instance.OnPlayerButton;
            @PlayerButton.performed -= instance.OnPlayerButton;
            @PlayerButton.canceled -= instance.OnPlayerButton;
            @CoinSlot.started -= instance.OnCoinSlot;
            @CoinSlot.performed -= instance.OnCoinSlot;
            @CoinSlot.canceled -= instance.OnCoinSlot;
        }

        public void RemoveCallbacks(ILinuxGameplayActions instance)
        {
            if (m_Wrapper.m_LinuxGameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILinuxGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_LinuxGameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LinuxGameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LinuxGameplayActions @LinuxGameplay => new LinuxGameplayActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_Newaction;
    public struct UIActions
    {
        private @BGSCabinetInput m_Wrapper;
        public UIActions(@BGSCabinetInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_UI_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IGameplayActions
    {
        void OnStick(InputAction.CallbackContext context);
        void OnBottomRow1(InputAction.CallbackContext context);
        void OnBottomRow2(InputAction.CallbackContext context);
        void OnTopRow1(InputAction.CallbackContext context);
        void OnTopRow2(InputAction.CallbackContext context);
        void OnTopRow3(InputAction.CallbackContext context);
        void OnBottomRow3(InputAction.CallbackContext context);
        void OnPlayerButton(InputAction.CallbackContext context);
        void OnCoinSlot(InputAction.CallbackContext context);
    }
    public interface ILinuxGameplayActions
    {
        void OnStick(InputAction.CallbackContext context);
        void OnBottomRow1(InputAction.CallbackContext context);
        void OnBottomRow2(InputAction.CallbackContext context);
        void OnTopRow1(InputAction.CallbackContext context);
        void OnTopRow2(InputAction.CallbackContext context);
        void OnTopRow3(InputAction.CallbackContext context);
        void OnBottomRow3(InputAction.CallbackContext context);
        void OnPlayerButton(InputAction.CallbackContext context);
        void OnCoinSlot(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
